config/routes.rb
Echowaves::Application.routes.draw do

  devise_for :users

  resources :users, :only => [:index, :show] do
    resources :followerships, :only => [:create, :destroy]
  end

  resources :convos, :only => [:index, :show, :new, :create] do
    # nested message, essential to support restful resources for messages
    resources :messages, :only => [:index, :show, :create]
  end

  resources :visits, :only => [:index]
  resources :updates, :only => [:index]
  resources :invitations, :only => [:index, :new, :create, :destroy] do
    put :accept
  end

  root :to => "welcome#index"
  match '/welcome', :to => 'welcome#index', :as => :welcome

  resource :socket, :only => [:subscribe, :unsubscribe] do
    member do
      post :subscribe
      post :unsubscribe
    end
  end

  resources :subscriptions, :only => [:index, :create, :destroy ]


end

app/views/shared/_convo_menu.html.erb
<div id="convo_settings"><%= link_to image_tag("/images/gear.png"), "#", :id => "convo_menu_link" %></div>

<div id="convo_menu" class="hidden">
  <!-- user actions -->
  <!-- ... -->
  <!-- admin actions -->
  <% if @convo.manageable_by_user?(@current_user) %>
  <% end %>
</div>

app/views/shared/_dashboard.html.erb
<div class="highlight_box item5">
	<%if current_user%>
	news:
	<div id="updated_subscriptions">loading  updates...</div>
	recent:
	<div id="visited_convos">loading visited convos...</div>
	<%end%>
</div>

app/views/shared/_footer.html.erb
<div id="copy">
  &copy;2011 echowaves | terms of service | about us
</div>

app/views/shared/_global_js_vars.html.erb
<script type="text/javascript">

      //----------------------------------------------------------------------
      // global settings
      //----------------------------------------------------------------------

      var g = {
        convoId      : "<%= @convo ? @convo.id : 0 %>"
       ,userGravatar : "<%= user_signed_in? ? gravatar_url(current_user.email) : "/images/icons/default-avatar-60.png" %>"
      }

</script>

app/views/shared/_header.html.erb
<div id="header">
  <%= link_to(image_tag("/images/echowaves.png", :alt => "echowaves logo"), root_path) %>
  <ul id="main_nav">
    <% if user_signed_in? %>
      <li class="red"><%= link_to("new convo", new_convo_path)%></li>
      <li><%= link_to "logout", destroy_user_session_path %></li>
      <li><%= link_to "profile", user_path(current_user), :id => 'nav_profile_link' %></li>
    <% else %>
      <li class="red"><%= link_to "login", new_user_session_path %></li>
      <li class="red"><%= link_to "signup", new_user_registration_path %></li>
    <% end %>
    <li><a href=""><img src="/images/glass.png"/></a></li>
    <li><%= link_to image_tag("/images/users.png"), users_path, :id => 'nav_users_link' %></li>

    <li><%= link_to image_tag("/images/chat.png"), convos_path, :id => 'nav_convos_link' %></li>
  </ul>
  <div class="clear"></div>
</div>

app/views/shared/_message_area.html.erb
<% if user_signed_in?  %>
<textarea id="message_area" cols="80"></textarea>
<% end %>

app/views/shared/_sidepanel.html.erb
<%if user_signed_in?%>
  <div class="highlight_box item5">
  	news:
  	<div id="updated_subscriptions">loading  updates...</div>
  </div>

  <div class="highlight_box item5">
  	recent:
  	<div id="visited_convos">loading visited convos...</div>
  </div>
<%end%>

app/views/shared/_templates.html.erb
<div style="display: none" id="templates">

  <div id="message_template" class="message">
    <div class="avatar"><%= link_to image_tag("/images/icons/default-avatar-60.png", :width => 30, :height => 30, :class => "avatar_img"), "#" %></div>
    <div class="body"></div>
    <div class="meta">
      <span class="date"><%= link_to "00:00AM", "#" %> - </span>
      <span class="username"></span>
    </div>
    <div class="clear"></div>
  </div>

</div>