config/routes.rb
Echowaves::Application.routes.draw do

  devise_for :users

  resources :users, :only => [:index, :show] do
    resources :followerships, :only => [:create, :destroy]
  end

  resources :convos, :only => [:index, :show, :new, :create] do
    # nested message, essential to support restful resources for messages
    resources :messages, :only => [:index, :show, :create]
  end

  resources :visits, :only => [:index]
  resources :updates, :only => [:index]
  resources :invitations, :only => [:index, :new, :create, :destroy] do
    put :accept
  end

  root :to => "welcome#index"
  match '/welcome', :to => 'welcome#index', :as => :welcome

  resource :socket, :only => [:subscribe, :unsubscribe] do
    member do
      post :subscribe
      post :unsubscribe
    end
  end

  resources :subscriptions, :only => [:index, :create, :destroy ]


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js">
	<head>
		<title>echowaves</title>
		<meta http-equiv="Content-Type" content="text/xhtml; charset=utf-8" />
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= render :partial => 'shared/global_js_vars' %>
    <%= csrf_meta_tag %>
	</head>
	<body>
		<div class="layout {layout: {type: 'border', hgap: 3, vgap: 3}}">
			<div class="north">
		        <%= render :partial => 'shared/header' %>
			</div>
			<div class="center page {layout: {type: 'border', hgap: 0, vgap: 0, resize: false}}">
			  	<div class="center" id="convo_content">
		          	<p class="notice"><%= notice %></p>
		          	<p class="alert"><%= alert %></p>
		          	<%= yield %>
			  	</div>
			</div><!-- center -->
			<div class="south">
		        <%= render :partial => 'shared/footer' %>
			</div>
		</div>
	</body>
</html>

app/views/layouts/convo_one_panel.html.erb
<!DOCTYPE html>
<html class="no-js">
<head>
    <title>echowaves</title>
    <meta http-equiv="Content-Type" content="text/xhtml; charset=utf-8" />
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= socky :client_id => (user_signed_in? ? current_user.id : nil), :channels => "convo_#{@convo.id}" %>
    <%= render :partial => 'shared/global_js_vars' %>
    <%= csrf_meta_tag %>
</head>
<body>
    <div class="layout {layout: {type: 'border', hgap: 3, vgap: 3}}">
        <div class="north">
            <%= render :partial => 'shared/header' %>
        </div>

        <div class="center convo <%= @convo.confidential? ? 'confidential' : 'social' %> {layout: {type: 'border', hgap: 0, vgap: 0, resize: false}}">
            <div class="north warn" id="convo_header">
                <%= @convo.title %>
                <div id="convo_settings"><%= link_to "back", convo_path(@convo) %></div>
                <div class="clear"></div>
            </div>
            <div class="center" id="convo_content">
              <p class="notice"><%= notice %></p>
              <p class="alert"><%= alert %></p>
              <%= yield %>
            </div>
            <div class="south"></div>
        </div><!-- center & convo -->

        <div class="east sidebar {layout: {type: 'grid', hgap: 3, vgap: 6, columns: 1, rows: 1}}">
            <div class="box {layout: {type: 'border', hgap: 0, vgap: 0, resize: false}}" id="component-1">
                <div class="north box_header">
                    this is not a dashboard
                </div>
                <div class="center box_content_round">
                    <%= render :partial => "shared/sidepanel" %>
                </div>
            </div>
        </div><!-- east -->

        <div class="south">
            <%= render :partial => 'shared/footer' %>
        </div>
    </div>

</body>

</html>

app/views/layouts/convo_two_panels.html.erb
<!DOCTYPE html>
<html class="no-js">
<head>
	<title>echowaves</title>
	<meta http-equiv="Content-Type" content="text/xhtml; charset=utf-8" />
	<%= stylesheet_link_tag "application" %>
	<%= javascript_include_tag "application" %>
	<%= socky :client_id => (user_signed_in? ? current_user.id : nil), :channels => "convo_#{@convo.id}" %>
	<%= render :partial => 'shared/global_js_vars' %>
	<%= csrf_meta_tag %>
</head>
<body>

	<div class="layout {layout: {type: 'border', hgap: 3, vgap: 3}}">
		<div class="north">
			<%= render :partial => 'shared/header' %>
		</div>

		<div class="center convo <%= @convo.confidential? ? 'confidential' : 'social' %> {layout: {type: 'border', hgap: 0, vgap: 0, resize: false}}">
			<div class="north warn" id="convo_header">
				<%= @convo.title %>
				<div id="convo_settings"><%= link_to "back", convo_path(@convo) %></div>
				<div class="clear"></div>
			</div>
			<div class="center" id="convo_content">
				<p class="notice"><%= notice %></p>
				<p class="alert"><%= alert %></p>
				<%= yield %>
			</div>
			<div class="south">
			</div>
		</div><!-- center & convo -->

		<div class="east sidebar {layout: {type: 'grid', hgap: 3, vgap: 6, columns: 1, rows: 1}}">
			<div class="box {layout: {type: 'border', hgap: 0, vgap: 0, resize: false}}" id="component-2">
				<%= yield :secondary_panel %>
			</div>

			<div class="box {layout: {type: 'border', hgap: 0, vgap: 0, resize: false}}" id="component-1">
				<div class="north box_header">not a dashboard</div>
				<div class="center box_content_round">
					<%= render :partial => "shared/sidepanel" %>
				</div>

			</div>

		</div><!-- east -->

		<div class="south">
			<%= render :partial => 'shared/footer' %>
		</div>
	</div>

</body>

</html>

app/views/layouts/messages.html.erb
<!DOCTYPE html>
<html class="no-js">
<head>
	<title>echowaves</title>
	<meta http-equiv="Content-Type" content="text/xhtml; charset=utf-8" />
	<%= stylesheet_link_tag "application" %>
	<%= javascript_include_tag "application" %>
	<%= socky :client_id => (user_signed_in? ? current_user.id : nil), :channels => "convo_#{@convo.id}" %>
	<%= csrf_meta_tag %>
	<%= render :partial => 'shared/global_js_vars' %>
</head>
<body>

	<%= render :partial => 'shared/templates' %>

	<div class="layout {layout: {type: 'border', hgap: 3, vgap: 3}}">
		<div class="north">
			<%= render :partial => 'shared/header' %>
		</div>

		<div class="center convo <%= @convo.confidential? ? 'confidential' : 'social' %> {layout: {type: 'border', hgap: 0, vgap: 0, resize: false}}">
			<div class="north warn" id="convo_header">
				<%= @convo.title %>

				<% if user_signed_in? %>
				<%= subscribe_or_unsubscribe_link(:convo => @convo, :user => current_user) %>
				<% end %>

				<%= link_to "#{@convo.subscriptions.size} subscribers", subscriptions_path(:convo_id => @convo.id) %>

				<%= link_to 'invite', new_invitation_path(:convo_id => @convo.id) %>

				<%= render :partial => "shared/convo_menu" %>
				<div class="clear"></div>
			</div>
			<div class="center" id="convo_content">
				<p class="notice"><%= notice %></p>
				<p class="alert"><%= alert %></p>
				<%= yield %>
			</div>
			<div class="south" id="convo_footer">
				<%= render :partial => 'shared/message_area' %>
			</div>
		</div><!-- center & convo -->

		<div class="east sidebar {layout: {type: 'grid', hgap: 3, vgap: 6, columns: 1, rows: 1}}">
			<div class="box {layout: {type: 'border', hgap: 0, vgap: 0, resize: false}}" id="component-1">
				<div class="north box_header">not a dashboard</div>
				<div class="center box_content_round">
					<%= render :partial => "shared/sidepanel" %>
				</div>

			</div>

		</div><!-- east -->

		<div class="south">
			<%= render :partial => 'shared/footer' %>
		</div>
	</div>

</body>

</html>

app/views/layouts/updates.html.erb
<%= yield %>

app/views/layouts/visits.html.erb
<%= yield %>